import Home from './Home.jsx'
import About from './About.jsx'
import ContactUs from './ContactUs.jsx'
import Login from './Login/Login.jsx'
import ForgotPasswordPage from './ForgotPassword.jsx'
import Signup from './Signup/Signup.jsx'
import VerifyOTP from './VerifyOTP/VerifyOTP.jsx'
import Registration from './Registration/Registration.jsx'
import Matches from './Matches/Matches.jsx'
export { Home, About, ContactUs, Login, ForgotPasswordPage, Signup, VerifyOTP, Registration, Matches }